

export default {
  FETCH_MY_FILES_REQUEST: 'FETCH_MY_FILES_REQUEST',
  FETCH_MY_FILES_SUCCESS: 'FETCH_MY_FILES_SUCCESS',
  FETCH_MY_FILES_FAILURE: 'FETCH_MY_FILES_FAILURE',
  FETCH_SHAREPOINT_FILES_REQUEST: 'FETCH_SHAREPOINT_FILES_REQUEST',
  FETCH_SHAREPOINT_FILES_SUCCESS: 'FETCH_SHAREPOINT_FILES_SUCCESS',
  FETCH_SHAREPOINT_FILES_FAILURE: 'FETCH_SHAREPOINT_FILES_FAILURE',
  AUTH_O365_API: 'AUTH_O365_API'
};

